// Default mappings for icons

export const SUCC_DEFAULT_MAPPING = {
    'shaken': 'modules/succ/assets/icons/0-shaken.svg',
    'incapacitated': 'modules/succ/assets/icons/3-incapacitated.svg',
    'aiming': 'modules/succ/assets/icons/1-aiming.svg',
    'berserk': 'modules/succ/assets/icons/1-berserking.svg',
    'defending': 'modules/succ/assets/icons/1-defending.svg',
    'flying': 'modules/succ/assets/icons/1-flying.svg',
    'holding': 'modules/succ/assets/icons/1-holding.svg',
    'bound': 'modules/succ/assets/icons/2b-bound.svg',
    'entangled': 'modules/succ/assets/icons/2b-entangled.svg',
    'frightened': 'modules/succ/assets/icons/2c-frightened.svg',
    'distracted': 'modules/succ/assets/icons/2-distracted.svg',
    'encumbered': 'modules/succ/assets/icons/2-encumbered.svg',
    'prone': 'modules/succ/assets/icons/2-prone.svg',
    'stunned': 'modules/succ/assets/icons/2-stunned.svg',
    'vulnerable': 'modules/succ/assets/icons/2-vulnerable.svg',
    'the-drop': 'modules/succ/assets/icons/2-the_drop.svg',
    'bleeding-out': 'modules/succ/assets/icons/3-bleeding_out.svg',
    'diseased': 'modules/succ/assets/icons/3-diseased.svg',
    'heart-attack': 'modules/succ/assets/icons/3-heart_attack.svg',
    'on-fire': 'modules/succ/assets/icons/3-on_fire.svg',
    'poisoned': 'modules/succ/assets/icons/3-poisoned.svg',
    'cover-shield': 'modules/succ/assets/icons/4-shield.svg',
    'cover': 'modules/succ/assets/icons/4-cover.svg',
    'reach': 'modules/succ/assets/icons/5-reach.svg',
    'torch': 'modules/succ/assets/icons/5-torch.svg',
    'invisible': 'modules/succ/assets/icons/m-invisible.svg',
    'smite': 'modules/succ/assets/icons/m-smite.svg',
    'protection': 'modules/succ/assets/icons/m-protection.svg'
}

export const SUCC_DEFAULT_ADDITIONAL_CONDITIONS = {
    irradiated: {
        id: 'irradiated',
        label: 'Irradiated',
        icon: 'modules/succ/assets/icons/0-irradiated.svg'
    },
    boost: {
        id: 'boost',
        icon: 'modules/succ/assets/icons/m-boost.svg'
    },
    lower: {
        id: 'lower',
        icon: 'modules/succ/assets/icons/m-lower.svg'
    },
}

export const SUCC_DEFAULT_SWADE_LINKS = {
    //These are the compendium links for the entries in the SWADE Module
    'shaken': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03damageeffect00#shaken]',
    'incapacitated': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03damageeffect00#incapacitation]',
    'aiming': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03aim00000000000#aim]',
    'berserk': '@UUID[Compendium.swade-core-rules.swade-edges.Xv6TAc0VcnkEqt20]',
    'defending': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03defend00000000#defend]',
    'flying': '@UUID[Compendium.swade-core-rules.swade-specialabilities.bvNxxTm14d8tD9aF]',
    'holding': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03hold0000000000#hold]',
    'bound': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03boundandenta00#bound-and-entangled]',
    'entangled': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03boundandenta00#bound-and-entangled]',
    'frightened': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04fear0000000000#fear]',
    'distracted': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03distractedan00#distracted-and-vulnerable]',
    'encumbered': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor02gear00.JournalEntryPage.02gearnotes00000#encumbrance]',
    'prone': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03prone000000000#prone]',
    'stunned': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03stunned0000000#stunned]',
    'vulnerable': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03distractedan00#distracted-and-vulnerable]',
    'the-drop': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03thedrop0000000#the-drop]',
    'bleeding-out': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03damageeffect00#incapacitation]',
    'diseased': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04disease0000000#disease]',
    'heart-attack': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04fear0000000000#fear-table$1]',
    'on-fire': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04fire0000000000#fire]',
    'poisoned': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04poison00000000#poison]',
    'cover-shield': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor02gear00.JournalEntryPage.02shields0000000#shields]',
    'cover': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03coverandobst00#cover-and-obstacles]',
    'reach': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor02gear00.JournalEntryPage.02reach000000000#reach]',
    'torch': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor03rules0.JournalEntryPage.03illumination00#illumination]',
    'invisible': '@UUID[Compendium.swade-core-rules.swade-powers.iS3duGwyTywaMOF7]',
    'smite': '@UUID[Compendium.swade-core-rules.swade-powers.AlGYtSZmjUDRfUGM]',
    'protection': '@UUID[Compendium.swade-core-rules.swade-powers.9Ia8jJNOCy0z7yXn]',
    'irradiated': '@UUID[Compendium.swade-core-rules.swade-rules.swadecor04theadv.JournalEntryPage.04radiation00000#radiation]',
    'boost': '@UUID[Compendium.swade-core-rules.swade-powers.FSwGNyzYvYRMhOkV]',
    'lower': '@UUID[Compendium.swade-core-rules.swade-powers.FSwGNyzYvYRMhOkV]'
}

export const SUCC_DEFAULT_SWPF_LINKS = {
    //These are the compendium links for the entries in the SWADE Module
    'shaken': '@Compendium[swpf-core-rules.swpf-rules.zzh3mj1QDalp0RYf]',
    'incapacitated': '@Compendium[swpf-core-rules.swpf-rules.3MljFFSMHnSPozbs]',
    'aiming': '@Compendium[swpf-core-rules.swpf-rules.sUYNS218qHShciXd]',
    'berserk': '@Compendium[swpf-core-rules.swpf-edges.Niz9w9swd6R68uAN]',
    'defending': '@Compendium[swpf-core-rules.swpf-rules.zW0vCtrPnvUbt0ns]',
    'flying': '@Compendium[swpf-core-rules.swpf-abilities.DYArX60CmykJvnfx]',
    'holding': '@Compendium[swpf-core-rules.swpf-rules.QzTAIH1jeyKyDwGI]',
    'bound': '@Compendium[swpf-core-rules.swpf-rules.wrmQPMAc5xvUPNwc]',
    'entangled': '@Compendium[swpf-core-rules.swpf-rules.wrmQPMAc5xvUPNwc]',
    'frightened': '@Compendium[swpf-core-rules.swpf-rules.Wz3EGUxCmSngGaR2]',
    'distracted': '@Compendium[swpf-core-rules.swpf-rules.DlAApOqk5Qygv0gU]',
    'encumbered': '@Compendium[swpf-core-rules.swpf-rules.yZutkhibo6To97ET]',
    'prone': '@Compendium[swpf-core-rules.swpf-rules.TsPTxdhNeJrrGTo3]',
    'stunned': '@Compendium[swpf-core-rules.swpf-rules.y7c8OOE2yhMJxVxm]',
    'vulnerable': '@Compendium[swpf-core-rules.swpf-rules.DlAApOqk5Qygv0gU]',
    'the-drop': '@Compendium[swpf-core-rules.swpf-rules.The Drop]',
    'bleeding-out': '@Compendium[swpf-core-rules.swpf-rules.mo17NvZSvFEO13hW]',
    'diseased': '@Compendium[swpf-core-rules.swpf-rules.sYmRb0jl47kTw673]',
    'heart-attack': '@Compendium[swpf-core-rules.swpf-rules.Wz3EGUxCmSngGaR2]',
    'on-fire': '@Compendium[swpf-core-rules.swpf-rules.gUtNJpX9g7XrB35y]',
    'poisoned': '@Compendium[swpf-core-rules.swpf-rules.szDZYOgjOJaEBMX9]',
    'cover-shield': '@Compendium[swpf-core-rules.swpf-rules.I890twJBUMA8SYUU]',
    'cover': '@Compendium[swpf-core-rules.swpf-rules.t7bveP3o2a3qz6sB]',
    'reach': '@Compendium[swpf-core-rules.swpf-rules.xyQaQ5r4IdqsoiUK]',
    'torch': '@Compendium[swpf-core-rules.swpf-rules.AZ16LJMpcOFSGgRn]',
    'invisible': '@Compendium[swpf-core-rules.swpf-powers.K76tydAgjnrtu3tq]',
    'smite': '@Compendium[swpf-core-rules.swpf-powers.8bh4SI0ARxZsfPL1]',
    'protection': '@Compendium[swpf-core-rules.swpf-powers.ZErveSbnXzsKMXoA]',
    'boost': '',
    'lower': ''
}

export const SUCC_DEFAULT_SWPF_LINKS_NEW = {
    'shaken': '@Compendium[swpf-core-rules.swpf-rules.QTDpA978FoGy0P3k]',
    'incapacitated': '@Compendium[swpf-core-rules.swpf-rules.lXS1wuvs9W779bGk]',
    'aiming': '@Compendium[swpf-core-rules.swpf-rules.Xg9Yy4S7DJIZoC3y]',
    'berserk': '@Compendium[swpf-core-rules.swpf-edges.TjR4gwORZ7E82Wqr]',
    'defending': '@Compendium[swpf-core-rules.swpf-rules.X8svEW536smwgrq6]',
    'flying': '@Compendium[swpf-core-rules.swpf-abilities.lZVhdNhW8bG0GcVz]',
    'holding': '@Compendium[swpf-core-rules.swpf-rules.76sT257yFavaXoqT]',
    'bound': '@Compendium[swpf-core-rules.swpf-rules.bwF5pzEwQSXAYlEb]',
    'entangled': '@Compendium[swpf-core-rules.swpf-rules.bwF5pzEwQSXAYlEb]',
    'frightened': '@Compendium[swpf-core-rules.swpf-rules.xyuYSRJHwsNIsQcH]',
    'distracted': '@Compendium[swpf-core-rules.swpf-rules.1tH7slDGScGgCMfx]',
    'encumbered': '@Compendium[swpf-core-rules.swpf-rules.HazvTAWCK8sclzSF]',
    'prone': '@Compendium[swpf-core-rules.swpf-rules.sEybdrp4m3RBl08B]',
    'stunned': '@Compendium[swpf-core-rules.swpf-rules.IJaHhmhsGYz2yDrG]',
    'vulnerable': '@Compendium[swpf-core-rules.swpf-rules.1tH7slDGScGgCMfx]',
    'the-drop': '@Compendium[swpf-core-rules.swpf-rules.The Drop]',
    'bleeding-out': '@Compendium[swpf-core-rules.swpf-rules.vJA1HKIF2a34cRYd]',
    'diseased': '@Compendium[swpf-core-rules.swpf-rules.DqEfiYnnjJqBUb0b]',
    'heart-attack': '@Compendium[swpf-core-rules.swpf-rules.xyuYSRJHwsNIsQcH]',
    'on-fire': '@Compendium[swpf-core-rules.swpf-rules.UK0GSlV6M7BYYooQ]',
    'poisoned': '@Compendium[swpf-core-rules.swpf-rules.K2i9FQnRwcPO7Tjo]',
    'cover-shield': '@Compendium[swpf-core-rules.swpf-rules.oRihpCsgXjbVEOHx]',
    'cover': '@Compendium[swpf-core-rules.swpf-rules.n9yodHBw85sUOGhS]',
    'reach': '@Compendium[swpf-core-rules.swpf-rules.Gv6C7S5II2rHp84I]',
    'torch': '@Compendium[swpf-core-rules.swpf-rules.StKylZawGhVutsR8]',
    'invisible': '@Compendium[swpf-core-rules.swpf-powers.FKymxmrz9ugwfFmb]',
    'smite': '@Compendium[swpf-core-rules.swpf-powers.LiY5yCQkOOKz9T2L]',
    'protection': '@Compendium[swpf-core-rules.swpf-powers.4yGOUiND8lW5cKly]',
    'boost': '@Compendium[swpf-core-rules.swpf-powers.hBfpNdcd1WBsszu3]',
    'lower': '@Compendium[swpf-core-rules.swpf-powers.hBfpNdcd1WBsszu3]'
    }