// Default mappings for icons

export const SUCC_DEFAULT_MAPPING = {
    'shaken': 'modules/succ/assets/icons/0-shaken.svg',
    'incapacitated': 'modules/succ/assets/icons/3-incapacitated.svg',
    'aiming': 'modules/succ/assets/icons/1-aiming.svg',
    'berserk': 'modules/succ/assets/icons/1-berserking.svg',
    'defending': 'modules/succ/assets/icons/1-defending.svg',
    'flying': 'modules/succ/assets/icons/1-flying.svg',
    'holding': 'modules/succ/assets/icons/1-holding.svg',
    'bound': 'modules/succ/assets/icons/2b-bound.svg',
    'entangled': 'modules/succ/assets/icons/2b-entangled.svg',
    'frightened': 'modules/succ/assets/icons/2c-frightened.svg',
    'distracted': 'modules/succ/assets/icons/2-distracted.svg',
    'encumbered': 'modules/succ/assets/icons/2-encumbered.svg',
    'prone': 'modules/succ/assets/icons/2-prone.svg',
    'stunned': 'modules/succ/assets/icons/2-stunned.svg',
    'vulnerable': 'modules/succ/assets/icons/2-vulnerable.svg',
    'bleeding-out': 'modules/succ/assets/icons/3-bleeding_out.svg',
    'diseased': 'modules/succ/assets/icons/3-diseased.svg',
    'heart-attack': 'modules/succ/assets/icons/3-heart_attack.svg',
    'on-fire': 'modules/succ/assets/icons/3-on_fire.svg',
    'poisoned': 'modules/succ/assets/icons/3-poisoned.svg',
    'cover-shield': 'modules/succ/assets/icons/4-shield.svg',
    'cover': 'modules/succ/assets/icons/4-cover.svg',
    'reach': 'modules/succ/assets/icons/5-reach.svg',
    'torch': 'modules/succ/assets/icons/5-torch.svg',
    'invisible': 'modules/succ/assets/icons/m-invisible.svg',
    'smite': 'modules/succ/assets/icons/m-smite.svg',
    'protection': 'modules/succ/assets/icons/m-protection.svg'
}

export const SUCC_DEFAULT_SWADE_LINKS = {
    //These are the compendium links for the entries in the SWADE Module
    'shaken': 'swade-core-rules.swade-rules.30TJKevSbgxK6jQy',
    'incapacitated': 'swade-core-rules.swade-rules.30TJKevSbgxK6jQy',
    'aiming': 'swade-core-rules.swade-rules.Fxh6qdmOiHPAO0VK',
    'berserk': 'swade-core-rules.swade-edges.GdQ2ptJFFVleMX1Z',
    'defending': 'swade-core-rules.swade-rules.ghXOj9Rpuw7vSQpu',
    'flying': 'swade-core-rules.swade-rules.E1iVZqDIqKhbo8kX',
    'holding': 'swade-core-rules.swade-rules.v5io2xKJNNM0US1H',
    'bound': 'swade-core-rules.swade-rules.sTArFBzbesQkjLVg',
    'entangled': 'swade-core-rules.swade-rules.sTArFBzbesQkjLVg',
    'frightened': 'swade-core-rules.swade-rules.jaYcLBJnBk1ai5EH',
    'distracted': 'swade-core-rules.swade-rules.vuud75GDkKL3NW10',
    'encumbered': 'swade-core-rules.swade-rules.QhIMF8IRx263ockB',
    'prone': 'swade-core-rules.swade-rules.JhBfyamFYWMA4T93',
    'stunned': 'swade-core-rules.swade-rules.nHbnnGpaM8CgA5SI',
    'vulnerable': 'swade-core-rules.swade-rules.vuud75GDkKL3NW10',
    'bleeding-out': 'swade-core-rules.swade-rules.30TJKevSbgxK6jQy',
    'diseased': 'swade-core-rules.swade-rules.5n806Gfv7FpIbpWh',
    'heart-attack': 'swade-core-rules.swade-rules.jaYcLBJnBk1ai5EH',
    'on-fire': 'swade-core-rules.swade-rules.6cgunuVilk355mfE',
    'poisoned': 'swade-core-rules.swade-rules.492TZ3ZhWD452C3O',
    'cover-shield': 'swade-core-rules.swade-rules.kO7fFCYkcuYbUReS',
    'cover': 'swade-core-rules.swade-rules.854By7DpYevCCEfJ',
    'reach': 'swade-core-rules.swade-rules.Oy34lVkZJFE8uNrt',
    'torch': 'swade-core-rules.swade-rules.033IuoJfthTXBJ4w',
    'invisible': 'swade-core-rules.swade-powers.2ulSAv39yoZ7wHoH',
    'smite': 'swade-core-rules.swade-powers.trnibqLStQnp7hxu',
    'protection': 'swade-core-rules.swade-powers.DPOBFvSuvQgDWF2c'
}