// Default mappings for icons

export const SUCC_DEFAULT_MAPPING = {
    'shaken': 'modules/succ/assets/icons/0-shaken.svg',
    'incapacitated': 'modules/succ/assets/icons/3-incapacitated.svg',
    'aiming': 'modules/succ/assets/icons/1-aiming.svg',
    'berserk': 'modules/succ/assets/icons/1-berserking.svg',
    'defending': 'modules/succ/assets/icons/1-defending.svg',
    'flying': 'modules/succ/assets/icons/1-flying.svg',
    'holding': 'modules/succ/assets/icons/1-holding.svg',
    'bound': 'modules/succ/assets/icons/2b-bound.svg',
    'entangled': 'modules/succ/assets/icons/2b-entangled.svg',
    'frightened': 'modules/succ/assets/icons/2c-frightened.svg',
    'distracted': 'modules/succ/assets/icons/2-distracted.svg',
    'encumbered': 'modules/succ/assets/icons/2-encumbered.svg',
    'prone': 'modules/succ/assets/icons/2-prone.svg',
    'stunned': 'modules/succ/assets/icons/2-stunned.svg',
    'vulnerable': 'modules/succ/assets/icons/2-vulnerable.svg',
    'bleeding-out': 'modules/succ/assets/icons/3-bleeding_out.svg',
    'diseased': 'modules/succ/assets/icons/3-diseased.svg',
    'heart-attack': 'modules/succ/assets/icons/3-heart_attack.svg',
    'on-fire': 'modules/succ/assets/icons/3-on_fire.svg',
    'poisoned': 'modules/succ/assets/icons/3-poisoned.svg',
    'cover-shield': 'modules/succ/assets/icons/4-shield.svg',
    'cover': 'modules/succ/assets/icons/4-cover.svg',
    'reach': 'modules/succ/assets/icons/5-reach.svg',
    'torch': 'modules/succ/assets/icons/5-torch.svg',
    'invisible': 'modules/succ/assets/icons/m-invisible.svg',
    'smite': 'modules/succ/assets/icons/m-smite.svg',
    'protection': 'modules/succ/assets/icons/m-protection.svg'
}
